# version: 0.2

# phases:
#   pre_build:
#     commands:
#       - echo Logging in to Amazon ECR...
#       - aws --version
#       - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
#       - REPOSITORY_URI=436115465111.dkr.ecr.us-east-1.amazonaws.com/flask_rep
#       - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION)
#       - IMAGE_TAG=latest
#       - REPOSITORY_NAME=flask_rep
#   build:
#     commands:
#       - echo Build started on `date`
#       - echo Building the Docker image...
#       - echo Image_tag $IMAGE_TAG
#       - docker build -t $REPOSITORY_NAME:$IMAGE_TAG .
#       - docker tag $REPOSITORY_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG 
#   post_build:
#     commands:
#       - echo Build completed on `date`
#       - echo Pushing the Docker images...
#       - docker push $REPOSITORY_URI:$IMAGE_TAG
#       - echo Writing image definitions file...
#       - printf '[{"name":"flask_rep","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
# artifacts:
#     files: imagedefinitions.json

version: 0.2

phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    runtime-versions:
       python: 3.7
    #commands:
      # - There are no build commands
  pre_build:
    commands:
      - pip install -r requirements.txt
  post_build:
    commands:
      - python app.py